Added list of moves
JustinHuPrime/NPlanetary pull request #31
Opened 2021-02-07 06:58 UTC by JustinHuPrime

We now have a list of moves the client can send to the server

I removed some stretch goal stuff from the board and balance files

Closes #1

2021-02-08 21:03 UTC, wyndro requested changes
Just a small request for some documentation in the moves

2021-02-08 21:03 UTC, wyndro commented on src/common/Board.hs
> -    Nuke Int Vec2 Vec2 Int
So we are making ordinants stretch goals? I feel like that is a good choice.

2021-02-08 21:03 UTC, wyndro commented on src/common/Move.hs
> +    Attack Int Int
Please document what the two Ints are. I think one is the id of the ship but I don't know what the other is.

2021-02-08 23:53 UTC, JustinHuPrime commented on src/common/Move.hs
> +    Attack Int Int
Whoops! This is fixed in later commits, but the comment isn't. Fix committed.

2021-02-09 01:24 UTC, wyndro approved these changes

2021-02-09 01:24 UTC, JohannCooper approved these changes

2021-02-09 01:41 UTC, merged