Added initial board rendering
JustinHuPrime/NPlanetary pull request #71
Opened 2021-02-24 00:08 UTC by JohannCooper

I would really like some recommendations about better modules and where exactly to place custom shape rendering that expands what is available in GL.

2021-02-24 08:04 UTC, JustinHuPrime commented
Closes #5

2021-02-24 08:20 UTC, JustinHuPrime requested changes

2021-02-24 08:20 UTC, JustinHuPrime commented on src/client/Helper.hs
> +circle (x, y) radius vertices = map toPoint angles
Please add types to your functions
```suggestion
circle :: (Double, Double) -> Double -> Int -> [(Double, Double)]
circle (x, y) radius vertices = map toPoint angles
```

2021-02-24 08:20 UTC, JustinHuPrime commented on src/client/UI.hs
> +  board' <- readIORef board
Please use the boardLock when you're reading or writing from the board IORef!

2021-02-24 08:20 UTC, JustinHuPrime commented on src/client/UI.hs
> +import Graphics.Rendering.OpenGL.GL as GL
Why are you namespacing the GLUT and GL imports?

2021-02-24 08:20 UTC, JustinHuPrime commented on src/client/Helper.hs
> +      mapM_ (\(x, y) -> vertex (Vertex3 x y layer)) points
You don't need the second do-block - a do-block with one statement is equivalent to just that one statement
```suggestion
    renderPrimitive TriangleFan $ mapM_ (\(x, y) -> vertex (Vertex3 x y layer)) points
```

2021-02-24 08:20 UTC, JustinHuPrime commented on src/client/Helper.hs
> +renderFan points layer = do
```suggestion
renderFan :: [(Double, Double)] -> Double -> IO ()
renderFan points layer = do
```

2021-02-24 08:20 UTC, JustinHuPrime commented on src/client/Helper.hs
> +    radius' = radius / fromIntegral windowWidth
Shouldn't you be doing this with a transformation matrix in the shader instead?

2021-02-24 08:20 UTC, JustinHuPrime commented on src/client/Helper.hs
> +    layer = 0.0
```suggestion
    layer = -0.9
```

2021-02-24 08:20 UTC, JustinHuPrime commented on src/client/Helper.hs
> +    layer = 0.0
```suggestion
    layer = -0.9
```

Asteroids and Astronomical objects shouldn't ever overlap

2021-02-24 08:20 UTC, JustinHuPrime commented on src/client/Helper.hs
> +    layer = 0.0
This layer is good as-is

2021-02-24 08:20 UTC, JustinHuPrime commented on src/client/Helper.hs
> +-- TODO: change layers for each entity
```suggestion
```

2021-02-24 08:20 UTC, JustinHuPrime commented on NPlanetary.cabal
> +    Helper,
Perhaps call `Helper` something like `Renderer` instead?

2021-02-24 08:23 UTC, JustinHuPrime commented
I think your module splits are sensible.

2021-02-24 08:32 UTC, JustinHuPrime commented on src/client/Helper.hs
> +module Helper where
```suggestion
{-
Copyright 2020 Johann Cooper

SPDX-Licence-Identifier: AGPL-3.0-or-later

N-Planetary is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

N-Planetary is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with N-Planetary. If not, see <https://www.gnu.org/licenses/>.
-}

module Helper where
```

2021-02-24 08:33 UTC, JustinHuPrime requested changes
And also please remember to add copyright headers and add your name to the header of any file you change.

2021-02-24 21:31 UTC, JohannCooper commented on src/client/UI.hs
> +import Graphics.Rendering.OpenGL.GL as GL
That was for my own organization. I forgot to remove it before making the PR.

2021-02-24 21:59 UTC, JustinHuPrime requested changes

2021-02-24 21:59 UTC, JustinHuPrime commented on src/client/Renderer.hs
> +    radius' = radius / fromIntegral windowWidth
Shouldn't this sort of scaling be done using a transformation matrix in a shader?

2021-02-25 02:52 UTC, JustinHuPrime approved these changes

2021-02-25 03:51 UTC, wyndro approved these changes

2021-02-25 03:54 UTC, merged